services:
  # app:
  #   container_name: url-shortener
  #   image: junjiekoh/url-shortener:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - postgres
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST_DOCKER=db
  db:
    container_name: urlshortener-dev-db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${POSTGRES_DEV_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEV_PW}
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: always
    networks:
      - postgres
      
  cache:
    container_name: urlshortener-dev-cache
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"
    restart: always
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEV_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEV_PW}
    ports:
      - "5050:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: