"""Add a username column to url model

Revision ID: c18d8ea16ef6
Revises: 6a3f6a462cb1
Create Date: 2024-04-20 22:59:36.430749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c18d8ea16ef6'
down_revision: Union[str, None] = '6a3f6a462cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column("url", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url", "username")
    # ### end Alembic commands ###
